### ISSUE TITLE
Daycare library not found in version 2.1.6 and below.

### ISSUE THREAD

**Issue by jgmuchiri** [amdtllc/daycarepro#1]
If you are encountering an error that Daycare.php not found and your installation is on a Linux machine, go to `/application/libraries/` and rename `daycare.php` to `Daycare.php`

**Comment by ekelvi** [comment]
Unable to load the requested file: helpers/my_daycare_helper.php

**Comment by ekelvi** [comment]
WHY SO MANY BUGS IN YOUR SCRIPTS, IM FINDING IT VERY HARD TO SET IT UP FOR ALMOST 3 WEEKS NOW.PLEASE KINDLY SEND ME A WORKING SCRIPT .THANKS
