### ISSUE TITLE
FATAL ERROR

### ISSUE THREAD

**Issue by ekelvi** [amdtllc/daycarepro#4]
Fatal error: Call to undefined function get_option() in /home/eliada/com.eliada.com/application/models/Conf.php on line 11
Php Error
Severity: Error

Message: Call to undefined function get_option()

Filename: models/Conf.php

Line Number: 11

Backtrace:

**Comment by jgmuchiri** [comment]
Please make sure you have the latest daycare_helper.php in `/application/helper/daycare_helper.php`. That is where that function (get_option()) is found.

**Comment by ekelvi** [comment]
can you send it to me?

**Comment by jgmuchiri** [comment]
What version of the system are you using? Please start a ticket at https://amdtllc.com/support and include your  license text file.

**Comment by ekelvi** [comment]
where do i check for the version please

**Comment by jgmuchiri** [comment]
The zip file you downloaded is named in this format daycarepro_v1.2.3.zip "1.2.3" being the version number.

**Comment by ekelvi** [comment]
Please get me a working script with mysql, the CLI is not working for me.I
need the version with "rooms"

**Comment by ekelvi** [comment]
codecanyon-17652000-daycare-management-system

**Comment by jgmuchiri** [comment]
The link to ticket is https://support.amdtllc.com/. Please start a ticket so I can further assist you. Thanks

**Comment by ekelvi** [comment]
I have opened a ticket

**Comment by ekelvi** [comment]
LICENSE CERTIFICATE : Envato Market Item

==============================================

This document certifies the purchase of:

ONE REGULAR LICENSE

as defined in the standard terms and conditions on Envato Market.

Licensor's Author Username:

AMDTLLC

Licensee:

fingernet

Item Title:

Daycare Management System

Item URL:

https://codecanyon.net/item/daycare-management-system/17652000

Item ID:

17652000

Item Purchase Code:

fccf7ac8-9533-470f-8770-1232233e0f2e

Purchase Date:

2018-05-11 22:55:30 UTC

For any queries related to this document or license please contact Help
Team viahttps://help.author.envato.com

Envato Pty. Ltd. (ABN 11 119 159 741)

PO Box 16122, Collins Street West, VIC 8007, Australia

**Comment by ekelvi** [comment]
CAN I HAVE MY WORKING SCRIPT PLEASE?????????????????????????????

**Comment by ekelvi** [comment]
WHY CANT YOU RESOLVE YOUR ISSUESSSSSSSSSSSSSSSSSSS?

**Comment by jgmuchiri** [comment]
Your ticket has been received and will be addressed from the ticket system.  We are working on your ticket and verification of purchase.  Please refrain from posting same issue on different platforms and be patient.
